<html>

<head>
	<title><?php echo $headerTitle ?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo dirname($_SERVER['PHP_SELF']) ?>/templates/style.css">
	<link rel="stylesheet" type="text/css" href="<?php echo dirname($_SERVER['PHP_SELF']) ?>/../../src/md2html.css">

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src='https://www.googletagmanager.com/gtag/js?id=UA-560719-1'></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());
		gtag('config', 'UA-560719-1');
	</script>
</head>

<body>

	<article>
		<div style='margin-bottom: 20px;'>
			<div class="pageTitle" style="padding: 30px; font-size: 250%; font-weight: 600;">
				<?php echo $pageTitle; ?>
			</div>
			<div class="pageSubtitle" style="font-style: italic; margin-left: 30px; margin-top: -20px;">
				A demonstration of dynamic webpages generated by md2html
			</div>
		</div>

		<div class='titlebar'>
			<div class='titlebarButton'><a href='<?php echo dirname($_SERVER['PHP_SELF']) ?>/'>Home</a></div>
			<div class='titlebarButton'><a href='<?php echo dirname($_SERVER['PHP_SELF']) ?>/demo.md.html'>Demo</a></div>
			<div class='titlebarButton'><a href='<?php echo dirname($_SERVER['PHP_SELF']) ?>/folder1/folder2/readme.md.html'>Nested</a></div>
		</div>

		<div style='padding: 1px 2em 1em 2em;'>